from pathlib import Path

p = Path("docs/migrations/CURRENT_NFL_RESEARCH_HANDOFF.md")
text = p.read_text(encoding="utf-8")
marker = "# RB COMBINED INTEGRATION PRINCIPLE — DO NOT DROP EITHER TRACK"
block = "# RB COMBINED INTEGRATION PRINCIPLE — DO NOT DROP EITHER TRACK\n\n**This is a permanent sequencing/modeling rule and must survive future chats and new ideas.**\n\nTwo independently meaningful ideas must be pursued **together**, not one replacing the other when a new insight appears:\n\n1. **Production-equivalent parent stack:** reconstruct and score the complete canonical football stack historically (Bayesian/rules + MC + ML + State + calibrated ensemble where valid), because M94C is not production-equivalent and future RB work must improve the system we actually intend to run.\n2. **Enrich M94C with missing football information:** preserve M94C's validated team-opportunity/game-state capability, but feed/correct it with current pregame football state it was missing: timestamp-safe depth charts, RB1/RB2/RB3 hierarchy, lagged snaps/participation, current carry/touch shares, competing-RB strength/usage, injuries/availability, vacancy, roster/team changes, rookie/draft priors, backfield concentration, QB/non-RB rushing competition, OL availability and other justified football context.\n\nThese tracks are **complementary**. The project must test:\n\n- full production-equivalent stack alone;\n- enriched M94C opportunity/allocation module alone versus its parent;\n- full stack + enriched M94C opportunity/allocation;\n- then compatible retained modules such as M95F workload distribution, M95I vacancy/transition, and M95C/M96 environment/efficiency capabilities through precommitted ablations.\n\nDo not revert to whole-model replacement contests. New information should normally be evaluated as: **what specific capability can make the current parent system better, where does it help, what does it hurt, and can it coexist with the other validated pieces?** Replacement is allowed only if explicitly proven.\n\nProbability/distribution layers quantify uncertainty around the football state; they do not substitute for role, availability, allocation, team opportunity, runner ability, matchup or game-context knowledge.\n\nThe current next migration remains `RB-STACK1 — Production-Equivalent RB Historical Baseline + Integration Audit`, but RB-STACK1 must preserve the enriched-M94C/backfield-allocation track rather than postponing or forgetting it. Establish the production-equivalent parent first so the integration tests have the correct baseline, then immediately test the enriched M94C/allocation capability as an add-on to that parent.\n"
if marker in text:
    print("combined principle already present")
else:
    p.write_text(text.rstrip() + "\n\n" + block.rstrip() + "\n", encoding="utf-8")
    print("combined principle appended")
