# scripts/stadium_locations.py
STADIUM_LOCATION = {
    "BUF": {"stadium": "Highmark Stadium", "city": "Orchard Park", "state": "NY", "outdoor": True},
    "MIA": {"stadium": "Hard Rock Stadium", "city": "Miami Gardens", "state": "FL", "outdoor": True},
    "NE":  {"stadium": "Gillette Stadium", "city": "Foxborough", "state": "MA", "outdoor": True},
    "NYJ": {"stadium": "MetLife Stadium", "city": "East Rutherford", "state": "NJ", "outdoor": True},
    "CIN": {"stadium": "Paycor Stadium", "city": "Cincinnati", "state": "OH", "outdoor": True},
    "CLE": {"stadium": "Cleveland Browns Stadium", "city": "Cleveland", "state": "OH", "outdoor": True},
    "PIT": {"stadium": "Acrisure Stadium", "city": "Pittsburgh", "state": "PA", "outdoor": True},
    "BAL": {"stadium": "M&T Bank Stadium", "city": "Baltimore", "state": "MD", "outdoor": True},
    "HOU": {"stadium": "NRG Stadium", "city": "Houston", "state": "TX", "outdoor": False},
    "IND": {"stadium": "Lucas Oil Stadium", "city": "Indianapolis", "state": "IN", "outdoor": False},
    "JAX": {"stadium": "EverBank Stadium", "city": "Jacksonville", "state": "FL", "outdoor": True},
    "TEN": {"stadium": "Nissan Stadium", "city": "Nashville", "state": "TN", "outdoor": True},
    "KC":  {"stadium": "GEHA Field at Arrowhead Stadium", "city": "Kansas City", "state": "MO", "outdoor": True},
    "LAC": {"stadium": "SoFi Stadium", "city": "Inglewood", "state": "CA", "outdoor": False},
    "LV":  {"stadium": "Allegiant Stadium", "city": "Las Vegas", "state": "NV", "outdoor": False},
    "DEN": {"stadium": "Empower Field at Mile High", "city": "Denver", "state": "CO", "outdoor": True},

    "DAL": {"stadium": "AT&T Stadium", "city": "Arlington", "state": "TX", "outdoor": False},
    "PHI": {"stadium": "Lincoln Financial Field", "city": "Philadelphia", "state": "PA", "outdoor": True},
    "WSH": {"stadium": "FedEx Field", "city": "Landover", "state": "MD", "outdoor": True},
    "NYG": {"stadium": "MetLife Stadium", "city": "East Rutherford", "state": "NJ", "outdoor": True},
    "GB":  {"stadium": "Lambeau Field", "city": "Green Bay", "state": "WI", "outdoor": True},
    "DET": {"stadium": "Ford Field", "city": "Detroit", "state": "MI", "outdoor": False},
    "CHI": {"stadium": "Soldier Field", "city": "Chicago", "state": "IL", "outdoor": True},
    "MIN": {"stadium": "U.S. Bank Stadium", "city": "Minneapolis", "state": "MN", "outdoor": False},
    "ATL": {"stadium": "Mercedes-Benz Stadium", "city": "Atlanta", "state": "GA", "outdoor": False},
    "NO":  {"stadium": "Caesars Superdome", "city": "New Orleans", "state": "LA", "outdoor": False},
    "TB":  {"stadium": "Raymond James Stadium", "city": "Tampa", "state": "FL", "outdoor": True},
    "CAR": {"stadium": "Bank of America Stadium", "city": "Charlotte", "state": "NC", "outdoor": True},
    "SF":  {"stadium": "Levi's Stadium", "city": "Santa Clara", "state": "CA", "outdoor": True},
    "SEA": {"stadium": "Lumen Field", "city": "Seattle", "state": "WA", "outdoor": True},
    "LAR": {"stadium": "SoFi Stadium", "city": "Inglewood", "state": "CA", "outdoor": False},
    "ARI": {"stadium": "State Farm Stadium", "city": "Glendale", "state": "AZ", "outdoor": False},
}
