# scripts/stadium_locations.py
STADIUM_LOCATION = {
    "BUF": {
        "stadium": "Highmark Stadium",
        "city": "Orchard Park",
        "state": "NY",
        "outdoor": True,
        "lat": 42.7738,
        "lon": -78.7868,
    },
    "MIA": {
        "stadium": "Hard Rock Stadium",
        "city": "Miami Gardens",
        "state": "FL",
        "outdoor": True,
        "lat": 25.958,
        "lon": -80.2389,
    },
    "NE": {
        "stadium": "Gillette Stadium",
        "city": "Foxborough",
        "state": "MA",
        "outdoor": True,
        "lat": 42.0909,
        "lon": -71.2643,
    },
    "NYJ": {
        "stadium": "MetLife Stadium",
        "city": "East Rutherford",
        "state": "NJ",
        "outdoor": True,
        "lat": 40.8136,
        "lon": -74.0745,
    },
    "CIN": {
        "stadium": "Paycor Stadium",
        "city": "Cincinnati",
        "state": "OH",
        "outdoor": True,
        "lat": 39.0954,
        "lon": -84.516,
    },
    "CLE": {
        "stadium": "Cleveland Browns Stadium",
        "city": "Cleveland",
        "state": "OH",
        "outdoor": True,
        "lat": 41.5061,
        "lon": -81.6995,
    },
    "PIT": {
        "stadium": "Acrisure Stadium",
        "city": "Pittsburgh",
        "state": "PA",
        "outdoor": True,
        "lat": 40.4468,
        "lon": -80.0158,
    },
    "BAL": {
        "stadium": "M&T Bank Stadium",
        "city": "Baltimore",
        "state": "MD",
        "outdoor": True,
        "lat": 39.2779,
        "lon": -76.6227,
    },
    "HOU": {
        "stadium": "NRG Stadium",
        "city": "Houston",
        "state": "TX",
        "outdoor": False,
        "lat": 29.6847,
        "lon": -95.4107,
    },
    "IND": {
        "stadium": "Lucas Oil Stadium",
        "city": "Indianapolis",
        "state": "IN",
        "outdoor": False,
        "lat": 39.7601,
        "lon": -86.1639,
    },
    "JAX": {
        "stadium": "EverBank Stadium",
        "city": "Jacksonville",
        "state": "FL",
        "outdoor": True,
        "lat": 30.324,
        "lon": -81.6373,
    },
    "TEN": {
        "stadium": "Nissan Stadium",
        "city": "Nashville",
        "state": "TN",
        "outdoor": True,
        "lat": 36.1665,
        "lon": -86.7713,
    },
    "KC": {
        "stadium": "GEHA Field at Arrowhead Stadium",
        "city": "Kansas City",
        "state": "MO",
        "outdoor": True,
        "lat": 39.0489,
        "lon": -94.4839,
    },
    "LAC": {
        "stadium": "SoFi Stadium",
        "city": "Inglewood",
        "state": "CA",
        "outdoor": False,
        "lat": 33.9535,
        "lon": -118.3391,
    },
    "LV": {
        "stadium": "Allegiant Stadium",
        "city": "Las Vegas",
        "state": "NV",
        "outdoor": False,
        "lat": 36.0909,
        "lon": -115.1833,
    },
    "DEN": {
        "stadium": "Empower Field at Mile High",
        "city": "Denver",
        "state": "CO",
        "outdoor": True,
        "lat": 39.7439,
        "lon": -105.0201,
    },
    "DAL": {
        "stadium": "AT&T Stadium",
        "city": "Arlington",
        "state": "TX",
        "outdoor": False,
        "lat": 32.7473,
        "lon": -97.0945,
    },
    "PHI": {
        "stadium": "Lincoln Financial Field",
        "city": "Philadelphia",
        "state": "PA",
        "outdoor": True,
        "lat": 39.9008,
        "lon": -75.1675,
    },
    "WSH": {
        "stadium": "FedEx Field",
        "city": "Landover",
        "state": "MD",
        "outdoor": True,
        "lat": 38.9077,
        "lon": -76.8645,
    },
    "NYG": {
        "stadium": "MetLife Stadium",
        "city": "East Rutherford",
        "state": "NJ",
        "outdoor": True,
        "lat": 40.8136,
        "lon": -74.0745,
    },
    "GB": {
        "stadium": "Lambeau Field",
        "city": "Green Bay",
        "state": "WI",
        "outdoor": True,
        "lat": 44.5013,
        "lon": -88.0622,
    },
    "DET": {
        "stadium": "Ford Field",
        "city": "Detroit",
        "state": "MI",
        "outdoor": False,
        "lat": 42.339,
        "lon": -83.0456,
    },
    "CHI": {
        "stadium": "Soldier Field",
        "city": "Chicago",
        "state": "IL",
        "outdoor": True,
        "lat": 41.8623,
        "lon": -87.6167,
    },
    "MIN": {
        "stadium": "U.S. Bank Stadium",
        "city": "Minneapolis",
        "state": "MN",
        "outdoor": False,
        "lat": 44.9737,
        "lon": -93.2577,
    },
    "ATL": {
        "stadium": "Mercedes-Benz Stadium",
        "city": "Atlanta",
        "state": "GA",
        "outdoor": False,
        "lat": 33.7554,
        "lon": -84.4009,
    },
    "NO": {
        "stadium": "Caesars Superdome",
        "city": "New Orleans",
        "state": "LA",
        "outdoor": False,
        "lat": 29.9509,
        "lon": -90.0814,
    },
    "TB": {
        "stadium": "Raymond James Stadium",
        "city": "Tampa",
        "state": "FL",
        "outdoor": True,
        "lat": 27.9759,
        "lon": -82.5033,
    },
    "CAR": {
        "stadium": "Bank of America Stadium",
        "city": "Charlotte",
        "state": "NC",
        "outdoor": True,
        "lat": 35.2251,
        "lon": -80.8528,
    },
    "SF": {
        "stadium": "Levi's Stadium",
        "city": "Santa Clara",
        "state": "CA",
        "outdoor": True,
        "lat": 37.403,
        "lon": -121.9702,
    },
    "SEA": {
        "stadium": "Lumen Field",
        "city": "Seattle",
        "state": "WA",
        "outdoor": True,
        "lat": 47.5952,
        "lon": -122.3316,
    },
    "LAR": {
        "stadium": "SoFi Stadium",
        "city": "Inglewood",
        "state": "CA",
        "outdoor": False,
        "lat": 33.9535,
        "lon": -118.3391,
    },
    "ARI": {
        "stadium": "State Farm Stadium",
        "city": "Glendale",
        "state": "AZ",
        "outdoor": False,
        "lat": 33.5277,
        "lon": -112.2626,
    },
}
