"""
Unified Model Stack Integration
--------------------------------
This module coordinates all predictive model systems (Bayesian, Monte Carlo, Markov, ML Ensemble)
to produce a single harmonized prediction output used by run_predictors.py.
"""

import pandas as pd
import traceback
from pathlib import Path

# Import model modules
from .bayes_hier import run_bayesian_model
from .markov import run_markov_model
from .monte_carlo import run_monte_carlo
from .ml_ensemble import run_ensemble_model
from .elite_rules import apply_elite_rules

def run_full_model(season: int = None, week: int = None):
    """Executes the unified model stack in sequence and merges outputs."""

    print("[model_stack_patch] 🚀 Running unified model stack...")

    try:
        # Load input metrics generated by make_metrics.py
        metrics_path = Path('data/make_metrics.csv')
        df = pd.read_csv(metrics_path)
        print(f"[model_stack_patch] Loaded metrics ({len(df)} rows)")

        results = []

        # Bayesian Hierarchical Model
        try:
            bayes_df = run_bayesian_model(df)
            bayes_df['model'] = 'Bayesian Hierarchical'
            results.append(bayes_df)
        except Exception as e:
            print(f"[model_stack_patch] ⚠️ Bayesian model failed: {e}")

        # Markov Receptions Model
        try:
            markov_df = run_markov_model(df)
            markov_df['model'] = 'Markov'
            results.append(markov_df)
        except Exception as e:
            print(f"[model_stack_patch] ⚠️ Markov model failed: {e}")

        # Monte Carlo Simulation Model
        try:
            mc_df = run_monte_carlo(df)
            mc_df['model'] = 'Monte Carlo'
            results.append(mc_df)
        except Exception as e:
            print(f"[model_stack_patch] ⚠️ Monte Carlo model failed: {e}")

        # ML Ensemble Model
        try:
            ml_df = run_ensemble_model(df)
            ml_df['model'] = 'ML Ensemble'
            results.append(ml_df)
        except Exception as e:
            print(f"[model_stack_patch] ⚠️ ML Ensemble failed: {e}")

        # Elite Rules (heuristic overrides)
        try:
            elite_df = apply_elite_rules(df)
            elite_df['model'] = 'Elite Rules'
            results.append(elite_df)
        except Exception as e:
            print(f"[model_stack_patch] ⚠️ Elite Rules failed: {e}")

        # Combine all results
        if results:
            final = pd.concat(results, ignore_index=True)
            out_path = Path('data/model_predictions_full.csv')
            final.to_csv(out_path, index=False)
            print(f"[model_stack_patch] ✅ Combined model output written to {out_path} ({len(final)} rows).")
        else:
            print("[model_stack_patch] ⚠️ No model results were produced.")

    except Exception as e:
        print(f"[model_stack_patch] ❌ Critical failure: {e}")
        traceback.print_exc()
