#!/usr/bin/env python3
"""Run canonical historical walk-forward while persisting the exact MC arrays.

This is a research-only adapter around ``component_predictions.build_mc_predictions``.
It does not replace the canonical historical builder or production pricing path.
Instead it captures the single SimulationResult generated by the canonical builder,
lets the canonical builder compute ``mc_proj`` normally, and then persists the same
player/market outcome arrays used by that computation.

The persisted representation is one compressed float32 matrix plus a CSV manifest
per season/week. Before writing, the adapter reconstructs the existing QB
attempt/share semantic conversion and fail-closes unless the reconstructed array
mean exactly reproduces the canonical ``mc_proj``. It then fail-closes again if
float32 serialization moves the mean outside a tight tolerance.
"""
from __future__ import annotations

import argparse
from pathlib import Path
from unittest.mock import patch

import numpy as np
import pandas as pd

from scripts._opponent_map import canon_team
from scripts.backtest import component_predictions
from scripts.backtest.walk_forward import _parse_weeks, run_walk_forward


_CANONICAL_BUILD_MC_PREDICTIONS = component_predictions.build_mc_predictions
IDENTITY_COLUMNS = ["season", "week", "team", "opponent", "player_clean_key", "market"]
SERIALIZATION_RTOL = 2e-6
SERIALIZATION_ATOL = 2e-5


def _converted_outcomes(sims, row: pd.Series) -> np.ndarray | None:
    """Reproduce the canonical post-lookup QB semantic conversion exactly."""
    market = str(row.get("market", ""))
    outcomes = component_predictions.lookup(sims, row, market)
    if outcomes is None or len(outcomes) == 0:
        return None
    out = np.asarray(outcomes, dtype=float)
    if market == "pass_yards":
        attempt_rate = pd.to_numeric(
            pd.Series([row.get("mc_pass_attempts_per_dropback")]), errors="coerce"
        ).iloc[0]
        share = pd.to_numeric(pd.Series([row.get("qb_pass_att_share")]), errors="coerce").iloc[0]
        if pd.notna(attempt_rate):
            out = out * float(np.clip(attempt_rate, 0.50, 1.00))
        if pd.notna(share):
            out = out * float(np.clip(share, 0.0, 1.0))
    return out


def persist_distribution_sidecar(
    metrics: pd.DataFrame,
    sims,
    *,
    season: int,
    week: int,
    seed: int,
    out_dir: Path,
) -> tuple[Path, Path]:
    """Persist exact historical MC arrays with fail-closed row identity."""
    if metrics is None or metrics.empty:
        raise RuntimeError(f"cannot persist empty simulation metrics for {season} W{week:02d}")

    required = {"team", "opponent", "player_clean_key", "market", "event_id", "mc_proj"}
    missing = sorted(required - set(metrics.columns))
    if missing:
        raise RuntimeError(f"simulation persistence metrics missing columns: {missing}")

    normalized = metrics.copy().reset_index(drop=True)
    normalized["team"] = normalized["team"].map(canon_team)
    normalized["opponent"] = normalized["opponent"].map(canon_team)
    normalized["player_clean_key"] = normalized["player_clean_key"].fillna("").astype(str).str.strip()
    normalized["market"] = normalized["market"].fillna("").astype(str).str.lower().str.strip()
    if normalized["team"].eq("").any() or normalized["opponent"].eq("").any():
        raise RuntimeError("simulation persistence contains uncanonicalizable team/opponent")
    if normalized["player_clean_key"].eq("").any() or normalized["market"].eq("").any():
        raise RuntimeError("simulation persistence contains blank player/market identity")

    row_keys = ["team", "opponent", "player_clean_key", "market"]
    if normalized.duplicated(row_keys).any():
        sample = normalized.loc[normalized.duplicated(row_keys, keep=False), row_keys].head(20)
        raise RuntimeError(f"simulation persistence duplicate row identity: {sample.to_dict('records')}")

    arrays: list[np.ndarray] = []
    manifest_rows: list[dict] = []
    expected_iterations = int(getattr(sims, "iterations", 0) or 0)
    if expected_iterations <= 0:
        raise RuntimeError("simulation persistence received invalid iteration count")

    stem = f"sim_distribution_{int(season)}_week_{int(week):02d}"
    npz_name = f"{stem}.npz"
    manifest_name = f"{stem}_manifest.csv"

    for _, row in normalized.iterrows():
        outcomes = _converted_outcomes(sims, row)
        if outcomes is None:
            continue
        if len(outcomes) != expected_iterations:
            raise RuntimeError(
                f"simulation iteration mismatch for {season} W{week:02d} "
                f"{row['player_clean_key']} {row['market']}: {len(outcomes)} != {expected_iterations}"
            )

        canonical_mc = pd.to_numeric(pd.Series([row.get("mc_proj")]), errors="coerce").iloc[0]
        exact_mean = float(np.mean(outcomes))
        if pd.isna(canonical_mc) or not np.isclose(
            exact_mean, float(canonical_mc), rtol=1e-12, atol=1e-12
        ):
            raise RuntimeError(
                "captured simulation does not reproduce canonical mc_proj "
                f"for {season} W{week:02d} {row['team']} {row['player_clean_key']} {row['market']}: "
                f"captured={exact_mean} canonical={canonical_mc}"
            )

        saved = np.asarray(outcomes, dtype=np.float32)
        stored_mean = float(saved.astype(np.float64).mean())
        if not np.isclose(
            stored_mean,
            float(canonical_mc),
            rtol=SERIALIZATION_RTOL,
            atol=SERIALIZATION_ATOL,
        ):
            raise RuntimeError(
                "float32 simulation serialization moved mc mean outside tolerance "
                f"for {season} W{week:02d} {row['team']} {row['player_clean_key']} {row['market']}: "
                f"stored={stored_mean} canonical={canonical_mc}"
            )

        array_row = len(arrays)
        arrays.append(saved)
        manifest_rows.append(
            {
                "season": int(season),
                "week": int(week),
                "team": str(row["team"]),
                "opponent": str(row["opponent"]),
                "player_clean_key": str(row["player_clean_key"]),
                "market": str(row["market"]),
                "event_id": str(row.get("event_id", "")),
                "array_row": int(array_row),
                "distribution_file": npz_name,
                "simulation_iterations": int(expected_iterations),
                "simulation_seed": int(seed),
                "canonical_mc_proj": float(canonical_mc),
                "stored_mc_proj": stored_mean,
                "stored_model_sd": float(np.std(saved.astype(np.float64), ddof=1))
                if len(saved) > 1
                else 0.0,
                "serialization_abs_error": abs(stored_mean - float(canonical_mc)),
            }
        )

    if not arrays:
        raise RuntimeError(f"simulation persistence captured zero arrays for {season} W{week:02d}")

    matrix = np.vstack(arrays).astype(np.float32, copy=False)
    if matrix.shape != (len(manifest_rows), expected_iterations):
        raise RuntimeError(
            f"simulation persistence matrix shape mismatch: {matrix.shape} "
            f"expected={(len(manifest_rows), expected_iterations)}"
        )

    manifest = pd.DataFrame(manifest_rows)
    if manifest.duplicated(IDENTITY_COLUMNS).any():
        sample = manifest.loc[
            manifest.duplicated(IDENTITY_COLUMNS, keep=False), IDENTITY_COLUMNS
        ].head(20)
        raise RuntimeError(f"simulation manifest duplicate identity: {sample.to_dict('records')}")

    out_dir.mkdir(parents=True, exist_ok=True)
    npz_path = out_dir / npz_name
    manifest_path = out_dir / manifest_name
    np.savez_compressed(npz_path, outcomes=matrix)
    manifest.to_csv(manifest_path, index=False)
    print(
        f"[distribution_v1] {season} W{week:02d} rows={len(manifest)} "
        f"iterations={expected_iterations} seed={seed} -> {npz_path}"
    )
    return npz_path, manifest_path


def build_mc_predictions_with_distribution(
    bundle,
    *,
    iterations: int = 5000,
    seed: int = 42,
    distribution_dir: Path,
) -> pd.DataFrame:
    """Call the canonical MC builder once, capture its SimulationResult, persist it."""
    captured: dict[str, object] = {}
    canonical_simulate = component_predictions.simulate

    def _capture_simulate(metrics, *, iterations=None, seed=None, allocation_trace=None):
        result = canonical_simulate(
            metrics,
            iterations=iterations,
            seed=seed,
            allocation_trace=allocation_trace,
        )
        captured["sims"] = result
        return result

    with patch.object(component_predictions, "simulate", new=_capture_simulate):
        metrics = _CANONICAL_BUILD_MC_PREDICTIONS(
            bundle,
            iterations=int(iterations),
            seed=int(seed),
        )

    sims = captured.get("sims")
    if sims is None:
        raise RuntimeError("canonical MC builder did not invoke simulate(); cannot persist distributions")

    persist_distribution_sidecar(
        metrics,
        sims,
        season=int(bundle.season),
        week=int(bundle.week),
        seed=int(seed),
        out_dir=Path(distribution_dir),
    )
    return metrics


def run_walk_forward_with_distributions(*, distribution_dir: Path, **kwargs) -> pd.DataFrame:
    """Use the existing walk-forward runner, swapping only the MC persistence adapter."""
    def _builder(bundle, *, iterations: int = 5000, seed: int = 42):
        return build_mc_predictions_with_distribution(
            bundle,
            iterations=iterations,
            seed=seed,
            distribution_dir=distribution_dir,
        )

    with patch.object(component_predictions, "build_mc_predictions", new=_builder):
        return run_walk_forward(**kwargs)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--season", type=int, required=True)
    p.add_argument("--prior-season", type=int, required=True)
    p.add_argument("--weeks", default="1-18")
    p.add_argument("--player-logs", type=Path, required=True)
    p.add_argument("--team-weekly", type=Path, required=True)
    p.add_argument("--schedule", type=Path, required=True)
    p.add_argument("--universe-dir", type=Path, required=True)
    p.add_argument("--injuries", type=Path, default=Path("data/backtests/injuries_history.csv"))
    p.add_argument("--weather", type=Path, default=Path("data/backtests/weather_history.csv"))
    p.add_argument("--out", type=Path, required=True)
    p.add_argument("--distribution-dir", type=Path, required=True)
    p.add_argument("--iterations", type=int, default=2000)
    args = p.parse_args()

    run_walk_forward_with_distributions(
        distribution_dir=args.distribution_dir,
        player_logs_path=args.player_logs,
        team_weekly_path=args.team_weekly,
        schedule_path=args.schedule,
        universe_dir=args.universe_dir,
        season=args.season,
        prior_season=args.prior_season,
        weeks=_parse_weeks(args.weeks),
        out_path=args.out,
        injuries_path=args.injuries,
        weather_path=args.weather,
        iterations=args.iterations,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
