name: Audit Only

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (if present)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run repo audit
        run: python scripts/utils/audit_repo.py

      - name: Upload audit artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audit-only-${{ github.run_id }}
          path: |
            data/*.csv
            outputs/**
          if-no-files-found: warn
